# Auteur      : Mehdi Salhi
# Auteur      : OpenZiti documentation
# Sujet       : Travail de Bachelor Zero Trust OpenZiti
# But         : Déploie une infrastructure OpenZiti
# No          : n2
# Description : 1 contrôleur, 3 routeur, 1 initialisteur, 1 serveur vidéo, 1
#               drone, 1 gcs, 1 base. Tous les fichiers sont sauvegardés dans 
# 		le répertoire local "vol", et monté dans le répertoire "persistent" 
# 		sur les containers
version: '2.4'
services:
  # openziti controller
  ziti-controller:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    env_file:
      - ./.env
    ports:
      - ${ZITI_EDGE_CONTROLLER_PORT:-1280}:${ZITI_EDGE_CONTROLLER_PORT:-1280}
      - ${ZITI_CTRL_PORT:-6262}:${ZITI_CTRL_PORT:-6262}
    environment:
      - ZITI_EDGE_IDENTITY_ENROLLMENT_DURATION=${ZITI_EDGE_IDENTITY_ENROLLMENT_DURATION}
      - ZITI_EDGE_ROUTER_ENROLLMENT_DURATION=${ZITI_EDGE_ROUTER_ENROLLMENT_DURATION}
    volumes:
      - type: bind
        source: ./vol
        target: /persistent
    entrypoint:
      - "/var/openziti/scripts/run-controller.sh"
    networks:
      internet:
         aliases:
           - ziti-edge-controller


  # controller init
  ziti-controller-init-container:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    depends_on:
      - ziti-controller
    environment:
      - ZITI_CONTROLLER_RAWNAME="${ZITI_CONTROLLER_RAWNAME}"
      - ZITI_EDGE_CONTROLLER_RAWNAME="${ZITI_EDGE_CONTROLLER_RAWNAME}"
    env_file:
      - ./.env
    networks:
      - internet
    volumes:
      - type: bind
        source: ./vol
        target: /persistent
    entrypoint:
      - "/var/openziti/scripts/run-with-ziti-cli.sh"
    command:
      - "/var/openziti/scripts/access-control.sh"

###################################
# Routers
###################################

  # edge router cloud
  ziti-edge-router-cloud:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    hostname: ziti-edge-router-cloud
    depends_on:
      - ziti-controller
    environment:
      - ZITI_CONTROLLER_RAWNAME="${ZITI_CONTROLLER_RAWNAME}"
      - ZITI_EDGE_CONTROLLER_RAWNAME="${ZITI_EDGE_CONTROLLER_RAWNAME}"
      - ZITI_EDGE_ROUTER_RAWNAME=${ZITI_EDGE_ROUTER_RAWNAME:-ziti-edge-router-cloud}
      - ZITI_EDGE_ROUTER_ROLES=public
    ports:
      - ${ZITI_EDGE_ROUTER_PORT:-3020}:${ZITI_EDGE_ROUTER_PORT:-3022}
      - 10082:10080
    networks:
      internet:
        aliases:
          - ziti-edge-router-cloud
    volumes:
      - type: bind
        source: ./vol
        target: /persistent
    entrypoint: ["bash", "-c", sleep 5 && /var/openziti/ziti-bin/ziti-router run /persistent/ziti-edge-router-cloud.yaml]
    #stdin_open: true
    #tty: true
    
  # edge router gcs
  ziti-edge-router-gcs:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    hostname: ziti-edge-router-gcs
    depends_on:
      - ziti-controller
    environment:
      - ZITI_CONTROLLER_RAWNAME="${ZITI_CONTROLLER_RAWNAME}"
      - ZITI_EDGE_CONTROLLER_RAWNAME="${ZITI_EDGE_CONTROLLER_RAWNAME}"
      - ZITI_EDGE_ROUTER_RAWNAME=${ZITI_EDGE_ROUTER_RAWNAME:-ziti-edge-router-gcs}
      - ZITI_EDGE_ROUTER_ROLES=public
    ports:
      - ${ZITI_EDGE_ROUTER_PORT:-3022}:${ZITI_EDGE_ROUTER_PORT:-3022}
      - 10080:10080
    networks:
      internet:
        aliases:
          - ziti-edge-router-gcs
      gcs:
        aliases:
          - ziti-edge-router-gcs
    volumes:
      - type: bind
        source: ./vol
        target: /persistent
    entrypoint: ["bash", "-c", sleep 5 && /var/openziti/ziti-bin/ziti-router run /persistent/ziti-edge-router-gcs.yaml]
    #stdin_open: true
    #tty: true
    
 # edge router base
  ziti-edge-router-base:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    hostname: ziti-edge-router-base
    depends_on:
      - ziti-controller
    environment:
      - ZITI_CONTROLLER_RAWNAME="${ZITI_CONTROLLER_RAWNAME}"
      - ZITI_EDGE_CONTROLLER_RAWNAME="${ZITI_EDGE_CONTROLLER_RAWNAME}"
      - ZITI_EDGE_ROUTER_RAWNAME=${ZITI_EDGE_ROUTER_RAWNAME:-ziti-edge-router-base}
      - ZITI_EDGE_ROUTER_ROLES=public
    ports:
      - ${ZITI_EDGE_ROUTER_PORT:-3021}:${ZITI_EDGE_ROUTER_PORT:-3022}
      - 10081:10080
    networks:
      internet:
        aliases:
          - ziti-edge-router-base
      base:
        aliases:
          - ziti-edge-router-base
  
    volumes:
      - type: bind
        source: ./vol
        target: /persistent
    entrypoint: ["bash", "-c", sleep 5 && /var/openziti/ziti-bin/ziti-router run /persistent/ziti-edge-router-base.yaml]
    #stdin_open: true
    #tty: true
 
    # console
  ziti-console:
    image: openziti/zac
    environment:
      - ZAC_SERVER_CERT_CHAIN=/persistent/pki/${ZITI_EDGE_CONTROLLER_HOSTNAME:-ziti-controller}-intermediate/certs/${ZITI_EDGE_CONTROLLER_HOSTNAME:-ziti-controller}-server.cert
      - ZAC_SERVER_KEY=/persistent/pki/${ZITI_EDGE_CONTROLLER_HOSTNAME:-ziti-controller}-intermediate/keys/${ZITI_EDGE_CONTROLLER_HOSTNAME:-ziti-controller}-server.key
      - PORTTLS=8443
    ports:
      - 1408:1408
      - 8443:8443
    working_dir: /usr/src/app
    volumes:
      - type: bind
        source: ./vol
        target: /persistent
    networks:
      - internet
      
    ##### machines
    # video server
  video-server:
    image: mehdi/rtmp-hls_server
    build:
      dockerfile: ./rtmp-hls-server/Dockerfile
      context: .
      network: host
    depends_on:
      - ziti-controller
      - ziti-edge-router-gcs
      - ziti-edge-router-cloud
      - ziti-edge-router-base
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 1935:1935
    volumes:
      - type: bind
        source: ./vol
        target: /persistent
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
    entrypoint:
      - "/persistent/tunnel-server.sh"
    networks: 
      internet:
        aliases:
          - video-server
          
  
  # drone
  drone:
    image: debian-bullslim
    build:
      dockerfile: ./Dockerfile_drone
      context: .
      network: host
    depends_on:
      - video-server
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./vol
        target: /persistent
    entrypoint:
      - "/persistent/tunnel-drone.sh"
    privileged: true
    stdin_open: true
    tty: true
    networks: 
      - internet
   
  
  # base
  base:
    image: debian-bullslim
    build:
      dockerfile: ./Dockerfile_base
      context: .
      network: host
    depends_on:
      - ziti-controller
      - ziti-edge-router-gcs
      - ziti-edge-router-cloud
      - ziti-edge-router-base
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./vol
        target: /persistent
    entrypoint:
      - "/persistent/tunnel-base.sh"
    privileged: true
    stdin_open: true
    tty: true
    networks: 
      - base
      - internet
   
  
  # GCS
  gcs:
    image: debian-bullslim
    build:
      dockerfile: ./Dockerfile_gcs
      context: .
      network: host
    depends_on:
      - ziti-controller
      - ziti-edge-router-gcs
      - ziti-edge-router-cloud
      - ziti-edge-router-base
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./vol
        target: /persistent
    entrypoint:
      - "/persistent/tunnel-gcs.sh"
    privileged: true
    stdin_open: true
    tty: true
    networks: 
      - gcs
      - internet

# networks
networks:
  internet:
    driver: bridge
  gcs:
    driver: bridge
  base:
    driver: bridge
