version: '2.4'
services:
  # video server
  video-server:
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
    networks:
      faketernet:
        #ipv4_address: 172.17.0.2
        aliases:
          - video-server

  # video streamer
  video-streamer:
    image: linuxserver/ffmpeg
    depends_on:
      - video-server
    build:
      dockerfile: Dockerfile
    networks:
      faketernet:
        aliases:
          - video-streamer
# networks
networks:
  faketernet:
    driver: bridge


volumes:
  video:

